---
title: "Info 201 Final Project"
author: "Aanyk Mann and Joey Kang"
date: '2022-08-08'
output: html_document
---

## Global Health Security

## Introduction

With the world we live in today, global health security plays a big role in how countries are able to operate, all the way from the leader to the normal civilians. We are interested in how to make best use of open datasets to spread awareness of global health security so it can be improved and help public safety. Specifically we are hoping to visualize and identify countries with low security indexes to inform ourselves and eventually develop ways to help improve their benchmarks. To do so, we referred to the *GHS Index* which has been gathering data from 2019 till now, and is responsible for creating index scores for each couturiers health security.

## Summary Table 

This table shows the global health index score of a pool of countries along with the year that the data was gathered. We extracted a random pool of 20 countries to give an example of how drastic the difference of safety can be within countries and even continents. The information displays how in countries within Africa there is a much lower index score versus those in Europe or North America. 